---
- name: "kitty | Install kitty"
  ansible.builtin.package:
    name: kitty
    state: latest
  # become: true

- name: "kitty | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

# - name: "kitty | Copy kitty.conf"
  # ansible.builtin.copy:
    # src: "kitty"
    # dest: "{{ ansible_user_dir }}/.config/"

- name: "kitty.conf | Create a symbolic link"
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.dotfiles/roles/kitty/files/kitty.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    state: link

- name: "kitty current-theme.conf | Create a symbolic link"
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.dotfiles/roles/kitty/files/current-theme.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/current-theme.conf"
    state: link

- name: "kitty kitty_tokyonight_night.conf | Create a symbolic link"
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.dotfiles/roles/kitty/files/kitty_tokyonight_night.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty_tokyonight_night.conf"
    state: link
