#!/usr/bin/bash

# List Commands
if ! [ -x "$(command -v lsd)" ]; then
	alias ls="ls --color=auto"
	alias l="ls -lAH"
	alias la="ls -a"
	alias ll="ls -al"
else
	alias ls="lsd"
	alias l="lsd -lAX"
	alias lt="ls --tree"
fi

alias grep='grep --color=auto'

# Confirmation
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias rm='rm -I --preserve-root'
