#!/usr/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shell.s

# for ble.sh must be at top
[[ $- == *i* ]] && source /usr/share/blesh/ble.sh --noattach

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines in the history
HISTCONTROL=ignoredups:ignorespace

# Auto "cd"
shopt -s autocd
# apped the the history file, don't overwrite it
shopt -s histappend

# setting history length
HISTSIZE=200
HISTFILESIZE=400
# need to move to profile
# export HISTFILE="${XDG_STATE_HOME}"/bash/history

source $HOME/.config/bash/bash_aliases
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias logseq='logseq --ozone-platform=wayland --disable-gpu'
PS1='[\u@\h \W]\$ '

export PATH=$PATH:/home/jb/.dotfiles/bin
export LEIN_HOME="$XDG_DATA_HOME"/lein
export NB_DIR="$XDG_DATA_HOME/nb"
export NBRC_PATH="$XDG_CONFIG_HOME/nbrc"
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
# to move yarn config file to XDG_CONFIG_HOME
# yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config

# color for less
# export LESS_TERMCAP_mb=$'\e[01;31m' # begin blinking
# export LESS_TERMCAP_md=$'\e[01;37m' # begin bold
# export LESS_TERMCAP_me=$'\e[0m'     # end all mode like so, us, mb, md, mr
# export LESS_TERMCAP_se=$'\e[0m'     # end standout-mode
# export LESS_TERMCAP_so=$'\e[45;93m' # start standout mode
# export LESS_TERMCAP_ue=$'\e[0m'     # end underline
# export LESS_TERMCAP_us=$'\e[4;93m'  # start underlining

export LESS_TERMCAP_mb=$(printf '\e[01;31m')       # enter blinking mode
export LESS_TERMCAP_md=$(printf '\e[01;38;5;75m')  # enter double-bright mode
export LESS_TERMCAP_me=$(printf '\e[0m')           # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m')           # leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m')       # enter standout mode
export LESS_TERMCAP_ue=$(printf '\e[0m')           # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;38;5;200m') # enter underline mode

eval "$(starship init bash)"

# for ble.sh must be at bottom
[[ ${BLE_VERSION-} ]] && ble-attach
