#!/usr/bin/bash

# List Commands
alias l="ls --color=auto"
alias l="ls -lAH --color=auto"
alias ls="ls -a --color=auto"
alias la="ls -a --color=auto"
alias ll="ls -al --color=auto"

alias grep='grep --color=auto'

# Confirmation
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias rm='rm -I --preserve-root'
